#Static variables
SF_WINDOW_ARENA = 'ARENA'
SF_WINDOW_CHARACTER = 'CHARACTER'
SF_WINDOW_OPTIONS = 'OPTIONS'
SF_WINDOW_TAVERN = 'TAVERN'
SF_WINDOWS = [SF_WINDOW_ARENA, SF_WINDOW_CHARACTER, SF_WINDOW_OPTIONS, SF_WINDOW_TAVERN]
SF_WINDOWS_HOTKEYS = {
    SF_WINDOW_ARENA: 'a',
    SF_WINDOW_CHARACTER: 'c',
    SF_WINDOW_OPTIONS: 'o',
    SF_WINDOW_TAVERN: 't',
}
SF_BASE_WINDOW = SF_WINDOW_OPTIONS #Base window